# pom文件依赖了jdbc-starter，但是没有指明数据源
# Cannot determine embedded database driver class for database type NONE
# 数据库版本的问题
spring:
  datasource:
    url: jdbc:mysql://124.70.157.93:3306/liangshi?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: dbls
    password: 123456t
# No Spring Session store is configured: set the 'spring.session.store-type' property
# 加入了SpringSession的集群session管理依赖，没有做默认配置，就会报错
  redis:
    host: 106.13.1.55
  session:
    store-type: REDIS




server:
  port: 8070
  session:
    timeout: 600 # 单位是秒

# Using default security password: e35ee0c3-67d0-440d-b5fd-28a8e1ea8377
# 加入spring-security的依赖之后默认会开启校验。没提供配置，会给你默认的配置默认的密码
security:
  basic:
    enabled: false


# 当我们使用我们这个安全模块的项目 配置了下面这个loginPage的时候，我们就用这个loginPage，没有做这个配置的时候，就用我们默认的标准登录页面。
# 最终完成的安全模块，提供很多配置项目，根据自己的情况去配置项目
      # 如果下面这段配置注释掉了，会直接用默认的
#rrong777:
#  security:
#    browser:
#      loginPage:
#        /demo-signIn.html
      # 如果这里没写 / 会转发到带BrowserSecurityController中读取了这个loginPage 会从http://localhost:8070/authentication/require
      # 转发到 http://localhost:8070/authentication/demo-signIn.html 然后重定向次数太多。 如果不明白的话 这里还有BrowserProperties中 去掉 / 就知道怎么回事了
#rrong777:
#  security:
#    browser:
#      loginType:
#        REDIRECT

#rrong777:
#  security:
#    code:
#      imageCode:
#        length: 6
##        上面应用级的配置，会覆盖掉默认配置
#        width: 100
#        url: /user,/user/*